import { Location } from '../shared/types/content';

/** Filter chips shown above the discovery list. "All" is prepended in the UI. */
export const LOCATION_FILTERS = [
  'Countryside',
  'Old Town',
  'Café Corner',
  'Riverside',
  'Coastal',
  'Canal',
  'Mountain',
] as const;

export const locations: Location[] = [
  {
    id: 'bibury',
    name: 'Bibury',
    country: 'England',
    region: 'Cotswolds',
    category: 'Cozy Village',
    filters: ['Countryside', 'Riverside', 'Café Corner'],
    tags: ['Peaceful', 'Romantic', 'Historic'],
    coords: { lat: 51.7582, lng: -1.8349 },
    short: 'Stone cottages draped in climbing roses line the crystal-clear River Coln.',
    description:
      'Bibury is one of those villages that feels as if it was built for slow mornings, quiet photographs, and soft countryside walks. Its honey-colored stone cottages, narrow lanes, and riverside scenery create a calm atmosphere that changes beautifully with the light. Arlington Row is the most recognizable part of the village, with old weavers’ cottages standing in a gentle line beside the water. The River Coln adds a peaceful rhythm to the place, with clear water, small bridges, green banks, and reflections that make the village feel almost painted.\n\nThe best way to experience Bibury is not to rush through it. It is a place for walking slowly, noticing small details, and letting the village mood unfold step by step. In spring and summer, flowers soften the stone walls and gardens. In autumn, golden leaves make the lanes warmer and quieter. In winter, the cottages feel especially storybook-like, with pale skies and a calm countryside silence.',
    howToSpendTime: [
      'Walk slowly along Arlington Row and notice the details of the old stone cottages.',
      'Sit beside the River Coln and enjoy the sound of the water.',
      'Take photos during golden hour when the cottages glow softly.',
      'Visit the old trout farm area and enjoy the peaceful countryside atmosphere.',
      'Explore the small lanes near the village center.',
      'Stop for tea, coffee, or a simple countryside lunch nearby.',
      'Look for small bridges and riverside viewpoints for calm photos.',
      'Visit St Mary’s Church and walk around the quiet churchyard.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'May–September for flowers and soft daylight.' },
      { label: 'Best mood', value: 'Romantic countryside walk.' },
      { label: 'Photo idea', value: 'Capture Arlington Row from a low riverside angle.' },
      { label: 'What to bring', value: 'Comfortable shoes, a light jacket, and a camera.' },
      { label: 'Quiet moment', value: 'Sit near the river for a few minutes before leaving.' },
    ],
  },
  {
    id: 'rye',
    name: 'Rye',
    country: 'England',
    region: 'East Sussex',
    category: 'Old Town',
    filters: ['Old Town', 'Café Corner'],
    tags: ['Cobbled', 'Literary', 'Nostalgic'],
    coords: { lat: 50.9497, lng: 0.7335 },
    short: 'Crooked cobbled lanes and half-timbered houses along famous Mermaid Street.',
    description:
      'Rye is a small historic town with crooked streets, old houses, antique shops, tearooms, and a coastal atmosphere that feels gentle and slightly mysterious. The town is known for Mermaid Street, where cobbled stones, half-timbered houses, brick walls, and climbing plants create one of the most atmospheric walking routes in England. Rye does not feel like a place made for fast sightseeing. It feels like a town for wandering without a strict plan, turning into quiet lanes, reading old signs, and stopping whenever a shop window or doorway catches your attention.\n\nThe charm of Rye is in its layers. There are medieval corners, literary associations, small galleries, old inns, independent shops, and views stretching toward the marshes. On cloudy days, the town feels especially cozy, with warm lights in windows and narrow streets that seem made for slow exploring.',
    howToSpendTime: [
      'Walk along Mermaid Street and photograph its old façades.',
      'Visit small antique shops and look for unusual objects.',
      'Stop at a tearoom or café for a warm drink.',
      'Explore the church area and climb for a view if available.',
      'Walk through the quieter side lanes away from the main route.',
      'Visit a small gallery or independent bookshop.',
      'Take photos of doors, windows, signs, and cobbled textures.',
      'Spend time near the old inns and imagine the town’s past.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Late morning or cloudy afternoon for soft light.' },
      { label: 'Best mood', value: 'Nostalgic old-town wandering.' },
      { label: 'Photo idea', value: 'Mermaid Street after light rain, when the cobbles shine.' },
      { label: 'What to bring', value: 'Flat shoes, because the cobbled streets can be uneven.' },
      { label: 'Perfect stop', value: 'A tearoom after a slow walk through the old center.' },
      { label: 'Small detail', value: 'Look closely at house names and old shop signs.' },
    ],
  },
  {
    id: 'colmar',
    name: 'Colmar',
    country: 'France',
    region: 'Alsace',
    category: 'Storybook Town',
    filters: ['Canal', 'Old Town', 'Café Corner'],
    tags: ['Colorful', 'Dreamy', 'Canal Walk'],
    coords: { lat: 48.0794, lng: 7.3585 },
    short: 'Pastel timber-framed houses reflect in the canals of Little Venice.',
    description:
      'Colmar is a town of colorful façades, flower-lined windows, canals, old bridges, and timber-framed houses that create a bright and fairytale-like atmosphere. The most famous area, often called Little Venice, is filled with waterside views, pastel houses, reflections, and narrow streets that feel made for slow exploration. Colmar is visually rich, but still cozy: every corner offers something small to notice, from painted shutters to hanging signs, from quiet courtyards to café terraces.\n\nThe town is especially beautiful when explored at walking pace. Its charm is not only in the famous photo spots, but also in the side streets where colors, textures, and old architecture create an intimate mood. In spring and summer, flowers make the streets feel fresh and cheerful. In winter, the town becomes warm and festive with glowing windows and seasonal decorations.',
    howToSpendTime: [
      'Walk through Little Venice and follow the canal views.',
      'Photograph the colorful timber-framed houses.',
      'Stop at a café terrace for coffee or dessert.',
      'Explore side streets away from the busiest route.',
      'Look for old shop signs and painted shutters.',
      'Visit a local bakery and try an Alsatian pastry.',
      'Take a slow evening walk when lights begin to glow.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Spring for flowers, winter for festive atmosphere.' },
      { label: 'Best mood', value: 'Bright fairytale city walk.' },
      { label: 'Photo idea', value: 'Canal reflections with pastel houses.' },
      { label: 'What to bring', value: 'A camera and comfortable walking shoes.' },
      { label: 'Quiet moment', value: 'Find a smaller bridge away from the main crowd.' },
    ],
  },
  {
    id: 'bruges',
    name: 'Bruges',
    country: 'Belgium',
    region: 'West Flanders',
    category: 'Medieval City',
    filters: ['Canal', 'Old Town', 'Café Corner'],
    tags: ['Canals', 'Chocolate', 'Historic'],
    coords: { lat: 51.2093, lng: 3.2247 },
    short: 'Medieval canals, arched bridges, chocolate shops and old brick streets.',
    description:
      'Bruges is a city of canals, bridges, old brick buildings, quiet courtyards, chocolate shops, and medieval streets that feel beautifully preserved. It has a calm romantic rhythm, especially in the early morning or evening when the streets become softer and the water reflects the façades. The city invites slow walking: over bridges, along canals, into small squares, through hidden-feeling courtyards, and past windows filled with chocolate, lace, books, and warm café light.\n\nBruges is not only about famous landmarks. Its cozy character is strongest in the smaller details: bicycles leaning against old walls, swans on the canals, narrow lanes, ivy-covered corners, and benches near the water. The city feels especially magical after light rain, when the stones and reflections make every corner look cinematic.',
    howToSpendTime: [
      'Walk along the canals and cross several small bridges.',
      'Visit a chocolate shop and choose a small treat.',
      'Sit near the water and watch boats pass by.',
      'Explore quiet courtyards and small side streets.',
      'Take photos of brick façades, windows, and reflections.',
      'Visit the central square and then move into calmer lanes.',
      'Try Belgian waffles or hot chocolate.',
      'Take an evening walk when the city lights turn warm.',
      'Save a favorite bench or bridge as a personal cozy point.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Early morning or evening for a calmer atmosphere.' },
      { label: 'Best mood', value: 'Romantic canal wandering.' },
      { label: 'Photo idea', value: 'A bridge with canal reflections after rain.' },
      { label: 'What to bring', value: 'A warm layer, because canal areas can feel cool.' },
      { label: 'Taste idea', value: 'Pair a slow walk with chocolate or waffles.' },
      { label: 'Quiet route', value: 'Leave the main square and follow smaller waterside streets.' },
    ],
  },
  {
    id: 'hallstatt',
    name: 'Hallstatt',
    country: 'Austria',
    region: 'Salzkammergut',
    category: 'Lakeside Village',
    filters: ['Mountain', 'Countryside'],
    tags: ['Mountain', 'Serene', 'Scenic'],
    coords: { lat: 47.5622, lng: 13.6493 },
    short: 'A dramatic lakeside village cradled between calm water and steep peaks.',
    description:
      'Hallstatt sits between a calm lake and steep mountains, creating one of the most peaceful and dramatic village settings in Europe. Wooden houses, narrow lanes, lakeside reflections, flower balconies, and mountain air make the village feel quiet, cinematic, and deeply atmospheric. It is a place where the view changes constantly: mist over the water, sunlight on rooftops, boats crossing the lake, and clouds moving between the mountain slopes.\n\nThe best experience in Hallstatt comes from slowing down and letting the landscape become part of the visit. Instead of only chasing the famous viewpoint, walk beside the lake, observe details in the village, sit quietly near the water, and enjoy the feeling of being surrounded by nature.',
    howToSpendTime: [
      'Walk along the lakeside path and enjoy the mountain reflections.',
      'Visit the classic viewpoint and take a wide scenic photo.',
      'Explore the narrow village lanes and small wooden houses.',
      'Sit beside the lake and watch the water change color.',
      'Take a short boat ride if the weather is calm.',
      'Visit a local café for coffee with a mountain view.',
      'Photograph flower balconies and rooftops.',
      'Walk slowly in the morning before the village becomes busier.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Early morning for calm views and soft light.' },
      { label: 'Best mood', value: 'Quiet mountain escape.' },
      { label: 'Photo idea', value: 'Lake reflection with the village and mountains.' },
      { label: 'What to bring', value: 'Comfortable shoes and a warm layer.' },
      { label: 'Quiet moment', value: 'Sit near the lake without opening the map for a few minutes.' },
      { label: 'Best season', value: 'Autumn for golden colors and cooler air.' },
    ],
  },
  {
    id: 'castle-combe',
    name: 'Castle Combe',
    country: 'England',
    region: 'Wiltshire',
    category: 'Stone Village',
    filters: ['Countryside'],
    tags: ['Timeless', 'Calm', 'Cottagecore'],
    coords: { lat: 51.4932, lng: -2.2299 },
    short: 'Honey-stone cottages, a quiet stream and a classic little bridge view.',
    description:
      'Castle Combe is a small village with stone cottages, gentle lanes, a quiet stream, and a deeply peaceful countryside character. It often feels like a place where modern noise has been turned down. The village does not need dramatic attractions to feel special. Its charm comes from balance: warm stone walls, simple cottage gardens, an old market cross, soft countryside colors, and a small bridge that creates one of the most classic village views.\n\nCastle Combe is best explored slowly, with attention to texture and atmosphere. The cottages, plants, doors, and stone details make it perfect for aesthetic photos, but the village also invites stillness. A short visit can feel like a small reset, especially if you choose one quiet corner and simply stay there for a moment.',
    howToSpendTime: [
      'Walk from the village center toward the small bridge.',
      'Photograph the stone cottages from different angles.',
      'Look for cottage gardens and seasonal flowers.',
      'Sit quietly near the stream if there is a peaceful spot.',
      'Visit the church and notice the old village details.',
      'Take a short countryside walk nearby.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Morning for fewer people and softer light.' },
      { label: 'Best mood', value: 'Quiet cottagecore escape.' },
      { label: 'Photo idea', value: 'The bridge view with cottages behind it.' },
      { label: 'What to bring', value: 'Simple walking shoes and a phone with enough storage.' },
      { label: 'Small detail', value: 'Notice the different tones of the old stone walls.' },
    ],
  },
  {
    id: 'dinan',
    name: 'Dinan',
    country: 'France',
    region: 'Brittany',
    category: 'Medieval Riverside Town',
    filters: ['Old Town', 'Riverside'],
    tags: ['Stone Streets', 'Artistic', 'Riverside'],
    coords: { lat: 48.4557, lng: -2.05 },
    short: 'Steep cobbled streets of artisan workshops leading down to a river port.',
    description:
      'Dinan is a medieval town in Brittany with steep cobbled streets, half-timbered houses, stone walls, artisan shops, and a beautiful riverside port. The town has a strong old-world atmosphere, but it also feels warm and lived-in. Its streets rise and fall dramatically, creating small views, hidden-feeling turns, and charming corners where old architecture and local life meet. The route down Rue du Jerzual toward the river is especially atmospheric, with workshops, galleries, and old façades along the way.\n\nDinan offers both elevated views and quiet riverside moments, making it feel varied but still cozy. You can spend time in the old center, then descend toward the port for a completely different mood: softer water, boats, cafés, and a calmer rhythm.',
    howToSpendTime: [
      'Walk down Rue du Jerzual and notice the old houses and workshops.',
      'Explore the medieval center and photograph timber-framed façades.',
      'Visit small artisan shops or galleries.',
      'Walk along the riverside port and watch the boats.',
      'Stop at a café near the water.',
      'Look for viewpoints from the town walls.',
      'Create a route from the old town to the river and save it.',
      'Take detail photos of doors, signs, stone walls, and shutters.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Late afternoon for warm light on the old streets.' },
      { label: 'Best mood', value: 'Medieval walk with a riverside ending.' },
      { label: 'Photo idea', value: 'Looking down a steep cobbled street with old façades.' },
      { label: 'What to bring', value: 'Comfortable shoes, because some streets are steep.' },
      { label: 'Quiet stop', value: 'The riverside port after exploring the upper town.' },
      { label: 'Creative idea', value: 'Save one artisan shop as a personal cozy point.' },
    ],
  },
  {
    id: 'portree',
    name: 'Portree',
    country: 'Scotland',
    region: 'Isle of Skye',
    category: 'Coastal Town',
    filters: ['Coastal'],
    tags: ['Colorful', 'Windy', 'Harbor'],
    coords: { lat: 57.4125, lng: -6.1942 },
    short: 'Bright harbor houses against sea air, cliffs and changing island skies.',
    description:
      'Portree is a small coastal town on the Isle of Skye, known for its colorful harbor houses, sea air, surrounding hills, and relaxed island atmosphere. The waterfront is the most recognizable part of the town, with bright façades standing against the harbor and cliffs. Portree feels cozy in a different way from soft village streets: it is windier, fresher, and more open, with a mood shaped by boats, weather, water, and changing skies.\n\nA visit can be simple and satisfying: walk to the harbor, watch the boats, drink something warm, take photos of the colored houses, and use the town as a starting point for nearby island landscapes. Even when the weather is cloudy, Portree feels memorable because the colors and sea views create a strong visual identity.',
    howToSpendTime: [
      'Walk down to the harbor and photograph the colorful houses.',
      'Watch the boats and changing reflections on the water.',
      'Stop for seafood, coffee, or a warm drink nearby.',
      'Take a short walk toward a viewpoint above the harbor.',
      'Save the harbor as a favorite scenic point.',
      'Use Portree as a calm base before exploring nearby landscapes.',
      'Take photos during cloudy weather for a moody coastal look.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Morning or early evening for softer harbor light.' },
      { label: 'Best mood', value: 'Fresh coastal escape.' },
      { label: 'Photo idea', value: 'Colorful houses with boats in the foreground.' },
      { label: 'What to bring', value: 'A windproof jacket.' },
      { label: 'Weather note', value: 'Cloudy skies can make the colors look richer.' },
      { label: 'Warm stop', value: 'Choose a small café after walking by the water.' },
    ],
  },
  {
    id: 'giethoorn',
    name: 'Giethoorn',
    country: 'Netherlands',
    region: 'Overijssel',
    category: 'Canal Village',
    filters: ['Canal'],
    tags: ['Waterways', 'Gentle', 'Fairytale'],
    coords: { lat: 52.74, lng: 6.0792 },
    short: 'A quiet maze of canals, wooden bridges and thatched-roof cottages.',
    description:
      'Giethoorn is a peaceful village shaped by canals, small bridges, thatched-roof houses, gardens, and quiet waterways. Instead of feeling like a typical street-based village, it feels like a soft waterside maze where movement happens by walking paths, bridges, and small boats. The atmosphere is gentle and scenic, especially when the water is calm and the gardens are full of greenery.\n\nThe village is ideal for slow discovery because the best details appear gradually: a wooden bridge, a flower-filled garden, a reflection, a small boat passing silently, or a cottage partly covered by plants. You can choose whether to walk, take a boat ride, photograph bridges, or simply enjoy the quiet canal views.',
    howToSpendTime: [
      'Walk along the canals and cross the small bridges.',
      'Take a quiet boat ride through the village waterways.',
      'Photograph thatched houses and garden reflections.',
      'Sit near the water and watch boats pass slowly.',
      'Explore smaller walking paths away from the busiest area.',
      'Save your favorite bridge as a personal point.',
      'Visit a waterside café if available.',
      'Create a calm photo route around the prettiest canal views.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Spring or early summer for gardens and greenery.' },
      { label: 'Best mood', value: 'Gentle waterside day.' },
      { label: 'Photo idea', value: 'A small bridge reflected in the canal.' },
      { label: 'What to bring', value: 'Comfortable shoes and a light rain jacket.' },
      { label: 'Quiet moment', value: 'Pause on a bridge and listen to the water.' },
      { label: 'Best experience', value: 'Combine a walk with a short boat ride.' },
    ],
  },
  {
    id: 'cesky-krumlov',
    name: 'Český Krumlov',
    country: 'Czech Republic',
    region: 'South Bohemia',
    category: 'Historic Town',
    filters: ['Old Town', 'Riverside'],
    tags: ['Castle View', 'River Bend', 'Artistic'],
    coords: { lat: 48.8127, lng: 14.3175 },
    short: 'Red rooftops wrapped by a curving river beneath a grand hilltop castle.',
    description:
      'Český Krumlov is a compact historic town wrapped by a curving river and watched over by a large castle complex. Its red rooftops, narrow lanes, old façades, small cafés, and viewpoints create a rich but cozy atmosphere. The town feels layered and theatrical, with streets that lead into courtyards, stairways, river views, and warm squares. It is scenic enough for dramatic photos, but small enough to explore slowly and personally.\n\nThe best part is how the town reveals itself from different heights and angles. From the riverside, it feels calm and intimate. From the castle area, it opens into a wide view of rooftops and winding streets.',
    howToSpendTime: [
      'Walk through the old town lanes without rushing.',
      'Visit the castle area and enjoy the view over red rooftops.',
      'Follow the river bend for peaceful scenery.',
      'Stop at a small café in the historic center.',
      'Take photos from elevated viewpoints.',
      'Explore courtyards and narrow passages.',
      'Save a favorite viewpoint on the map.',
      'Walk in the evening when the town lights become warmer.',
      'Look for handmade shops or small galleries.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Late spring or autumn for comfortable walking and soft colors.' },
      { label: 'Best mood', value: 'Historic town adventure with warm views.' },
      { label: 'Photo idea', value: 'Rooftops from the castle viewpoint.' },
      { label: 'What to bring', value: 'Comfortable shoes for stairs and uneven streets.' },
      { label: 'Quiet stop', value: 'A riverside bench away from the main square.' },
      { label: 'Route idea', value: 'Old town → river path → castle viewpoint → café.' },
    ],
  },
  {
    id: 'bourton-on-the-water',
    name: 'Bourton-on-the-Water',
    country: 'England',
    region: 'Cotswolds',
    category: 'Riverside Village',
    filters: ['Countryside', 'Riverside', 'Café Corner'],
    tags: ['Gentle', 'Scenic', 'Family Walk'],
    coords: { lat: 51.885, lng: -1.7549 },
    short: 'Low stone bridges cross the shallow River Windrush through the village.',
    description:
      'Bourton-on-the-Water is a soft and charming Cotswold village known for its shallow river, low stone bridges, honey-colored cottages, and peaceful walking paths. The River Windrush flows through the center, giving the village a calm and open feeling. Small bridges cross the water, ducks move slowly along the stream, and the old stone buildings create a warm countryside atmosphere that feels perfect for an easy day out.\n\nIt is not a dramatic destination; its beauty comes from the relaxed rhythm of the water, the softness of the architecture, and the simple pleasure of walking from bridge to bridge. On sunny days, the river becomes the heart of the village. On cloudy days, the stone cottages and tea rooms make the place feel even warmer.',
    howToSpendTime: [
      'Walk along the River Windrush and cross the small stone bridges.',
      'Sit near the water and enjoy the village atmosphere.',
      'Visit a tearoom or café for a warm drink and dessert.',
      'Photograph the cottages reflected in the shallow river.',
      'Explore small gift shops and local stores.',
      'Take a slow walk through the quieter lanes near the village center.',
      'Save a favorite bridge as a cozy map point.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Spring and summer for riverside walking.' },
      { label: 'Best mood', value: 'Gentle village afternoon.' },
      { label: 'Photo idea', value: 'A low bridge with cottages behind it.' },
      { label: 'What to bring', value: 'Comfortable shoes and a light jacket.' },
      { label: 'Quiet moment', value: 'Sit by the river and watch the water move slowly.' },
      { label: 'Best stop', value: 'A tearoom after walking through the village.' },
    ],
  },
  {
    id: 'eze',
    name: 'Eze',
    country: 'France',
    region: 'French Riviera',
    category: 'Hilltop Village',
    filters: ['Coastal'],
    tags: ['Sunny', 'Stone Paths', 'Sea View'],
    coords: { lat: 43.7286, lng: 7.3619 },
    short: 'A stone-path maze above the Mediterranean with sweeping sea views.',
    description:
      'Eze is a hilltop village above the Mediterranean, filled with narrow stone paths, old walls, small galleries, climbing plants, and breathtaking sea views. The village feels like a maze of warm stone, where every turn can lead to a small doorway, a flower-covered corner, or a viewpoint over the blue coastline. It has a more sunlit and elegant version of coziness: peaceful, scenic, and slightly magical.\n\nEze invites slow climbing, careful looking, and many pauses. The streets are steep, but the experience feels memorable because the village combines old architecture with bright Mediterranean air. It is especially beautiful in the morning, when the light is softer and the stone paths feel calmer.',
    howToSpendTime: [
      'Walk slowly through the narrow stone lanes.',
      'Visit small artisan shops and galleries.',
      'Stop at viewpoints to look over the Mediterranean.',
      'Photograph old doors, plants, stairs, and stone textures.',
      'Visit the exotic garden area for high panoramic views.',
      'Sit at a terrace café and enjoy the sunny village mood.',
      'Create a photo route from the village entrance to the top viewpoint.',
      'Save the best sea-view corner on the map.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Morning or late afternoon for softer light.' },
      { label: 'Best mood', value: 'Sunny stone-village escape.' },
      { label: 'Photo idea', value: 'A narrow lane opening toward the sea.' },
      { label: 'What to bring', value: 'Comfortable shoes, water, and sunglasses.' },
      { label: 'Route note', value: 'The paths can be steep, so explore slowly.' },
      { label: 'Quiet moment', value: 'Pause near a stone wall and watch the coastline below.' },
    ],
  },
  {
    id: 'lavenham',
    name: 'Lavenham',
    country: 'England',
    region: 'Suffolk',
    category: 'Medieval Village',
    filters: ['Old Town', 'Countryside'],
    tags: ['Timbered', 'Historic', 'Storybook'],
    coords: { lat: 52.1087, lng: 0.7966 },
    short: 'Crooked timber-framed houses lean over old medieval market streets.',
    description:
      'Lavenham is a medieval village with crooked timber-framed houses, colorful façades, old market streets, and a deeply historic atmosphere. The buildings lean and bend in unusual ways, giving the village a playful and storybook character. It feels like a place where the past is still visible in every beam, window, doorway, and roofline.\n\nLavenham’s cozy character comes from its imperfections: uneven lines, aged wood, soft colors, and small details that make each house feel individual. It is a wonderful location for a slow walking route, especially for people who love places that feel both charming and slightly whimsical.',
    howToSpendTime: [
      'Walk through the old village center and look at the timber-framed houses.',
      'Photograph the crooked façades and colorful walls.',
      'Visit a local café or tearoom.',
      'Explore the market square and surrounding lanes.',
      'Look for old doors, signs, beams, and small windows.',
      'Visit the church area for a peaceful historic stop.',
      'Create a short architecture photo challenge around the village.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Late morning for clear views of the façades.' },
      { label: 'Best mood', value: 'Historic village wandering.' },
      { label: 'Photo idea', value: 'A row of leaning timber-framed houses.' },
      { label: 'What to bring', value: 'A camera and comfortable walking shoes.' },
      { label: 'Small detail', value: 'Notice how every house has a slightly different shape.' },
      { label: 'Perfect stop', value: 'A warm drink after exploring the old streets.' },
    ],
  },
  {
    id: 'annecy',
    name: 'Annecy',
    country: 'France',
    region: 'Haute-Savoie',
    category: 'Lakeside Town',
    filters: ['Canal', 'Mountain', 'Café Corner'],
    tags: ['Canals', 'Alpine', 'Romantic'],
    coords: { lat: 45.8992, lng: 6.1294 },
    short: 'Flower-lined canals and pastel houses beside a clear alpine lake.',
    description:
      'Annecy is a lakeside town with clear water, pastel old buildings, flower-lined canals, mountain views, and a peaceful yet bright atmosphere. The old town feels gentle and scenic, with narrow streets, bridges, cafés, and water flowing through the center. The lake adds a fresh open feeling, while the surrounding mountains make the town feel calm and protected.\n\nA day in Annecy can include a slow walk through the old town, coffee near the canal, photos by the bridges, and quiet time beside the lake. It is a place where you can move between city charm and natural calm without needing a complicated route.',
    howToSpendTime: [
      'Walk through the old town and follow the canals.',
      'Photograph pastel buildings and flower-covered bridges.',
      'Sit beside the lake and watch the mountain reflections.',
      'Visit a small café near the water.',
      'Explore local markets if they are open.',
      'Take a relaxed lakeside walk.',
      'Save a favorite canal bridge as a cozy point.',
      'Watch the sunset near the lake.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Spring and summer for flowers and lake walks.' },
      { label: 'Best mood', value: 'Romantic water-and-mountain day.' },
      { label: 'Photo idea', value: 'Canal view with pastel buildings and flowers.' },
      { label: 'What to bring', value: 'Walking shoes and a light sweater.' },
      { label: 'Quiet stop', value: 'A bench near the lake away from the busiest streets.' },
      { label: 'Route idea', value: 'Old town canals → café stop → lakeside walk.' },
    ],
  },
  {
    id: 'monschau',
    name: 'Monschau',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    category: 'Old Town',
    filters: ['Old Town', 'Riverside'],
    tags: ['Timber Houses', 'River', 'Calm'],
    coords: { lat: 50.5546, lng: 6.24 },
    short: 'Timber-framed houses curve around a narrow river among green hills.',
    description:
      'Monschau is a small German town with timber-framed houses, a narrow river, stone bridges, and a cozy old-town atmosphere surrounded by green hills. The town feels compact and intimate, with streets that curve around the water and houses that seem to lean gently toward each other. It is especially atmospheric in cooler seasons, when mist, warm windows, and old façades make the town feel like a quiet illustration.\n\nThe best experience is to wander without rushing, follow the sound of the water, cross the bridges, and look back at the town from different angles. Every small turn feels like another cozy frame.',
    howToSpendTime: [
      'Walk along the river and cross the small bridges.',
      'Photograph timber-framed houses above the water.',
      'Explore the old town streets and small shops.',
      'Stop for coffee, cake, or a warm local snack.',
      'Walk up slightly for a wider view of the town.',
      'Visit during a cloudy day for a soft atmospheric mood.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Autumn or winter for a storybook atmosphere.' },
      { label: 'Best mood', value: 'Quiet old-town escape.' },
      { label: 'Photo idea', value: 'Timber houses reflected in the river.' },
      { label: 'What to bring', value: 'Warm clothes and comfortable shoes.' },
      { label: 'Quiet moment', value: 'Stand on a bridge and listen to the water.' },
      { label: 'Best detail', value: 'Look for windows, shutters, and old signs.' },
    ],
  },
  {
    id: 'sighisoara',
    name: 'Sighişoara',
    country: 'Romania',
    region: 'Transylvania',
    category: 'Citadel Town',
    filters: ['Old Town'],
    tags: ['Colorful', 'Medieval', 'Atmospheric'],
    coords: { lat: 46.2197, lng: 24.7964 },
    short: 'A colorful medieval citadel of towers, stairways and cobbled lanes.',
    description:
      'Sighişoara is a historic citadel town with colorful houses, cobbled streets, towers, old stairways, and a strong medieval atmosphere. The town sits above the surrounding area, giving it a slightly enclosed and protected feeling. Its streets are bright but aged, with pastel walls, old roofs, arched passages, and small squares that feel full of character.\n\nSighişoara can feel dramatic because of its citadel walls and towers, yet the small scale of the streets makes it personal and calm. It is a place for slow exploration, detail photography, and learning small facts about architecture, history, and local traditions.',
    howToSpendTime: [
      'Walk through the citadel streets and look at the colorful houses.',
      'Visit the clock tower area and enjoy the historic atmosphere.',
      'Climb old stairways for elevated views.',
      'Photograph doors, walls, rooftops, and narrow lanes.',
      'Stop at a small café in the old center.',
      'Read about the town’s medieval past.',
      'Save the most atmospheric street as a personal cozy point.',
      'Walk in the evening when the old walls feel quieter.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Late afternoon for warm colors on the walls.' },
      { label: 'Best mood', value: 'Medieval town discovery.' },
      { label: 'Photo idea', value: 'A pastel street leading toward a tower.' },
      { label: 'What to bring', value: 'Comfortable shoes for cobbles and stairs.' },
      { label: 'Small detail', value: 'Notice the different colors of the old façades.' },
      { label: 'Quiet stop', value: 'A side street away from the main square.' },
    ],
  },
  {
    id: 'manarola',
    name: 'Manarola',
    country: 'Italy',
    region: 'Liguria',
    category: 'Coastal Village',
    filters: ['Coastal'],
    tags: ['Colorful', 'Sea Cliff', 'Sunset'],
    coords: { lat: 44.106, lng: 9.729 },
    short: 'Colorful houses stacked into sea cliffs above the Ligurian coast.',
    description:
      'Manarola is a colorful coastal village built into steep cliffs above the Ligurian Sea. Its stacked houses, narrow paths, small harbor, rocky coastline, and sunset views create a bright and emotional travel mood. The village feels energetic because of its colors and sea setting, but it also has many cozy moments: small stairways, quiet corners above the water, café terraces, and warm evening light on the buildings.\n\nManarola is not just a viewpoint; it is a place to walk slowly, listen to the sea, notice laundry hanging between houses, and watch the colors change as the sun moves.',
    howToSpendTime: [
      'Walk through the narrow village paths and stairways.',
      'Visit the harbor and watch waves against the rocks.',
      'Photograph the colorful houses from the classic viewpoint.',
      'Stop for coffee, gelato, or a small meal with a sea view.',
      'Watch the sunset over the coastline.',
      'Save the best viewpoint as a favorite map point.',
      'Take detail photos of doors, plants, balconies, and painted walls.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Golden hour and sunset.' },
      { label: 'Best mood', value: 'Colorful coastal evening.' },
      { label: 'Photo idea', value: 'The village glowing above the sea.' },
      { label: 'What to bring', value: 'Comfortable shoes for stairs and uneven paths.' },
      { label: 'Quiet moment', value: 'Sit above the rocks and listen to the waves.' },
      { label: 'Weather note', value: 'Clear evenings make the colors especially warm.' },
    ],
  },
  {
    id: 'reine',
    name: 'Reine',
    country: 'Norway',
    region: 'Lofoten Islands',
    category: 'Fishing Village',
    filters: ['Coastal', 'Mountain'],
    tags: ['Nordic', 'Dramatic', 'Quiet'],
    coords: { lat: 67.9325, lng: 13.0896 },
    short: 'Red fishing cabins sheltered beneath sharp Nordic mountain peaks.',
    description:
      'Reine is a small fishing village surrounded by mountains, water, red cabins, and a powerful northern landscape. It feels remote, calm, and visually unforgettable. The village has a cozy character shaped by contrast: small warm houses against huge mountains, quiet harbor water beneath sharp peaks, and simple paths that open into grand views.\n\nReine is cozy because it feels sheltered inside a vast landscape. You can spend time walking near the harbor, photographing red cabins, watching clouds move over the mountains, and saving viewpoints for future trips.',
    howToSpendTime: [
      'Walk near the harbor and look at the red fishing cabins.',
      'Photograph mountains reflected in the water.',
      'Sit quietly and watch the weather change over the peaks.',
      'Explore nearby viewpoints if conditions are safe.',
      'Take a calm morning walk when the village is quiet.',
      'Save a favorite mountain-view point on the map.',
      'Drink something warm after walking in the cold air.',
      'Use the location as inspiration for a Nordic wallpaper.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Summer for easier walking, winter for snowy atmosphere.' },
      { label: 'Best mood', value: 'Quiet Nordic escape.' },
      { label: 'Photo idea', value: 'Red cabins with mountains behind them.' },
      { label: 'What to bring', value: 'Warm layers and waterproof shoes.' },
      { label: 'Weather note', value: 'Conditions can change quickly, so plan gently.' },
      { label: 'Quiet moment', value: 'Watch the clouds move across the mountain tops.' },
    ],
  },
  {
    id: 'piran',
    name: 'Piran',
    country: 'Slovenia',
    region: 'Adriatic Coast',
    category: 'Seaside Town',
    filters: ['Coastal', 'Old Town', 'Café Corner'],
    tags: ['Warm', 'Venetian', 'Seafront'],
    coords: { lat: 45.5283, lng: 13.5683 },
    short: 'Venetian-style lanes of warm stone open onto the Adriatic seafront.',
    description:
      'Piran is a small coastal town with narrow lanes, Venetian-style architecture, warm stone walls, sea views, and a relaxed Adriatic mood. The town feels bright and intimate, with streets that lead from small squares toward the waterfront. Its atmosphere is a mix of old-town charm and seaside calm, making it perfect for slow walks, terrace cafés, sunset views, and peaceful corners near the water.\n\nThe old town invites wandering without a strict plan, while the seafront gives a simple place to sit, watch boats, and enjoy the changing light. The town becomes especially beautiful in the evening when the walls turn golden and the water reflects the sunset.',
    howToSpendTime: [
      'Walk through the narrow old-town lanes.',
      'Visit the main square and observe the Venetian-style buildings.',
      'Sit by the sea and watch the water.',
      'Stop for coffee or dessert at a terrace café.',
      'Walk along the seafront during sunset.',
      'Climb toward a viewpoint for a wider town view.',
      'Photograph stone streets, shutters, balconies, and sea corners.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Late afternoon and sunset.' },
      { label: 'Best mood', value: 'Warm seaside wandering.' },
      { label: 'Photo idea', value: 'Old town rooftops with the sea behind them.' },
      { label: 'What to bring', value: 'Sunglasses, comfortable shoes, and a light layer.' },
      { label: 'Quiet stop', value: 'A bench or stone edge facing the water.' },
      { label: 'Taste idea', value: 'Choose a café near the seafront after walking.' },
    ],
  },
  {
    id: 'gdansk-old-town',
    name: 'Gdansk Old Town',
    country: 'Poland',
    region: 'Pomerania',
    category: 'Historic City',
    filters: ['Old Town', 'Café Corner', 'Riverside'],
    tags: ['Colorful', 'Riverfront', 'Merchant Streets'],
    coords: { lat: 54.352, lng: 18.6466 },
    short: 'Tall colorful merchant façades and riverfront paths lined with amber shops.',
    description:
      'Gdansk Old Town is full of tall colorful façades, historic gates, decorative details, riverfront paths, amber shops, cafés, and streets that feel both grand and cozy. The city has a strong maritime identity, but the old center also offers many soft corners: narrow side streets, warm windows, small courtyards, and peaceful spots beside the Motława River.\n\nGdansk offers more scale than a small village, but the experience can still feel cozy if the focus is on details and slow routes. Instead of only visiting the main street, follow the river, save favorite façades, look for quiet cafés, and build a personal walking route through atmospheric corners.',
    howToSpendTime: [
      'Walk along the Motława River and watch boats pass.',
      'Explore the colorful façades of the old town.',
      'Visit a café or bakery on a quieter side street.',
      'Photograph decorative doors, signs, windows, and rooftops.',
      'Look for amber shops and small local stores.',
      'Walk through historic gates and narrow passages.',
      'Save one favorite building façade as a cozy point.',
      'Take an evening walk when the riverfront lights turn on.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Evening for warm lights near the river.' },
      { label: 'Best mood', value: 'Historic city walk with river views.' },
      { label: 'Photo idea', value: 'Colorful façades from a low street angle.' },
      { label: 'What to bring', value: 'Comfortable shoes for a longer city walk.' },
      { label: 'Quiet route', value: 'Move from the main street into smaller side lanes.' },
      { label: 'Small detail', value: 'Look upward at the decorated rooflines.' },
    ],
  },
  {
    id: 'obidos',
    name: 'Óbidos',
    country: 'Portugal',
    region: 'Leiria District',
    category: 'Walled Town',
    filters: ['Old Town'],
    tags: ['White Houses', 'Flowers', 'Romantic'],
    coords: { lat: 39.3606, lng: -9.157 },
    short: 'Whitewashed lanes trimmed in blue and yellow inside old town walls.',
    description:
      'Óbidos is a small walled town with whitewashed houses, blue and yellow trim, stone lanes, flowers, old walls, and a romantic village atmosphere. The town feels like a compact maze of bright streets and cozy corners. Its walls give it a protected feeling, while the flowers and small houses make it warm and inviting.\n\nÓbidos can be explored slowly through its narrow lanes, with pauses for photos, small shops, viewpoints, and quiet corners. The contrast between white walls, colorful flowers, and old stone makes it especially beautiful when the light is gentle and the streets are not too busy.',
    howToSpendTime: [
      'Walk through the narrow whitewashed streets.',
      'Photograph flower-covered walls and colorful doorways.',
      'Explore small local shops and craft corners.',
      'Walk near the old town walls for wider views.',
      'Stop for a sweet local drink or dessert.',
      'Save a favorite doorway or flower street on the map.',
      'Take a slow morning walk before the town becomes busy.',
      'Look for quiet corners away from the central street.',
    ],
    cozyTips: [
      { label: 'Best time', value: 'Morning or late afternoon for soft light.' },
      { label: 'Best mood', value: 'Romantic walled-town walk.' },
      { label: 'Photo idea', value: 'White houses with bright flowers and old stone.' },
      { label: 'What to bring', value: 'Comfortable shoes for stone streets.' },
      { label: 'Quiet moment', value: 'Pause in a small side lane with flowers.' },
      { label: 'Color idea', value: 'Use the town’s white, blue, yellow, and pink tones for inspiration.' },
    ],
  },
];

export const getLocationById = (id: string) => locations.find(l => l.id === id);
